name: Run Arbitrage Bot

on:
  push:
  workflow_dispatch:
    inputs:
      mode:
        description: 'Test or Real Mode?'
        required: true
        default: 'test'
        type: choice
        options:
          - test
          - real

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v3
        
      - name: Run Test Command
        run: echo "Bot setup is working perfectly!"
